---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginxhello
  namespace: default
spec:
  interval: 1m0s
  secretRef:
    name: ghcr-charts-auth
  type: oci
  url: oci://ghcr.io/sarora20/charts
